ahoyapi: v2
commands:
  crawler:
    usage: Execut crwaler with php cli instead of swoole-cli
    cmd: |
      php /var/www/html/fork/src/crawler.php "$@"

  crawl:
    usage: Crawl site using siteone-crawler
    cmd: |
      mkdir -p /var/www/html/.siteone-crawler/reports
      mkdir -p /var/www/html/web
      ahoy crawler \
        --result-storage-dir=/var/www/html/.siteone-crawler/result-storage \
        --output-json-file="" \
        --output-text-file="" \
        --output-html-report=/var/www/html/.siteone-crawler/reports/%domain%.%datetime%.html \
        --http-cache-dir=/var/www/html/.siteone-crawler/http-cache \
        --offline-export-dir=/var/www/html/web \
        "$@"

  dac:
    usage: Crawl dac.com
    cmd: |
      ahoy crawl\
        --offline-export-remove-unwanted-code=0 \
        --max-non200-responses-per-basename=100 \
        --allowed-domain-for-crawling=ww.dac.com \
        --transform-url="/^ww\.dac\.com/ -> www.dac.com" \
        --memory-limit=4096M \
        --timeout=1200 \
        --offline-export-lowercase \
        --replace-content="/\/Portals\// -> /portals/" \
        --replace-content="/StandardMenu.css -> /standardmenu.css" \
        --replace-content="/SideMenu.css -> /sidemenu.css" \
        --replace-content="skeleton.css?v='+ version_date.getMonth() + '.' + version_date.getDate() + '-' + Math.floor(Math.random() * 1000) +' -> skeleton.27e842049f.css" \
        --replace-content="layout.css?v='+ version_date.getMonth() + '.' + version_date.getDate() + '-' + Math.floor(Math.random() * 1000) +' -> layout.27e842049f.css" \
        --replace-content="styles24.css?v='+ version_date.getMonth() + '.' + version_date.getDate() + '-' + Math.floor(Math.random() * 1000) +' -> styles24.27e842049f.css" \
        --replace-content="standardmenu.css?v='+ version_date.getMonth() + '.' + version_date.getDate() + '-' + Math.floor(Math.random() * 1000) +' -> standardmenu.27e842049f.css" \
        --replace-content="sidemenu.css?v='+ version_date.getMonth() + '.' + version_date.getDate() + '-' + Math.floor(Math.random() * 1000) +' -> sidemenu.27e842049f.css" \
        --url=https://www.dac.com \
        "$@"
